<script>
@@@file:src/includes/jquery.min.js@@@
@@@file:src/includes/jquery-ui.min.js@@@
@@@file:src/includes/popper.min.js@@@
@@@file:src/includes/bootstrap.min.js@@@
@@@file:src/includes/bootstrap-notify.min.js@@@
@@@file:src/includes/bootstrap-treeview.min.js@@@
@@@file:src/includes/datatables.min.js@@@
@@@file:src/includes/lodash.min.js@@@
@@@file:src/includes/classnames.js@@@
@@@file:src/includes/BootstrapMenu.min.js@@@
@@@file:src/includes/mustache.min.js@@@
@@@file:src/includes/ace.js@@@
@@@acedir:src/includes/ace@@@
@@@file:src/ifm.js@@@
</script>
